fix smrsh path & provide  more infomation after instlll successfully

diff --git a/xbaydns/tools/xdinit b/xbaydns/tools/xdinit
--- a/xbaydns/tools/xdinit
+++ b/xbaydns/tools/xdinit
@@ -15,43 +15,53 @@ chown -R named:named $BINDCHROOT/var/{run,dump,stats}
 touch $BINDCHROOT/var/log/named.log
 chown -R named:named $BINDCHROOT/var/log/named.log
 
+rm $BINDCHROOT/dev/{random,zero,null}
 mknod $BINDCHROOT/dev/random c 1 8
 mknod $BINDCHROOT/dev/zero c 1 5
 mknod $BINDCHROOT/dev/null c 1 3
 
 #2.init sync&cron enviroment 
-#-----------------------
+#===========================
 
+#2.1 prepare restrictive shell - smrsh
+#---------------------------
 if [ -x /usr/sbin/smrsh ];then
     # CentOS
-    SMRSH_PATH=/usr/sbin/smrsh
-    SMRSH_CMDDIR=/etc/smrsh
+    SMRSH_CMD=/usr/sbin/smrsh
+    SMRSH_ALLOWCMD_DIR=/etc/smrsh
 elif [ -x /usr/lib/sendmail.d/bin/smrsh ];then
     # OpenSuSE
-    SMRSH_PATH=/usr/lib/sendmail.d/bin/smrsh
-    SMRSH_CMDDIR=/usr/lib/sendmail.d/bin
+    SMRSH_CMD=/usr/lib/sendmail.d/bin/smrsh
+    SMRSH_ALLOWCMD_DIR=/usr/lib/sendmail.d/bin
 elif [ -x /usr/libexec/smrsh ];then
     # FreeBSD
-    SMRSH_PATH=/usr/libexec/smrsh
-    SMRSH_CMDDIR=/usr/libexec/sm.bin
+    SMRSH_CMD=/usr/libexec/smrsh
+    SMRSH_ALLOWCMD_DIR=/usr/libexec/sm.bin
 else
-    echo "Error: can't find smrsh,exiting!"
+    echo "Error: can't find smrsh, exiting!"
     exit 1
 fi
 
 if ! which rsync > /dev/null 2>&1 ; then
-    echo "Error: can't find rsync,exiting!"
+    echo "Error: can't find rsync, exiting!"
     exit 1
 fi
 
+if ! grep smrsh /etc/shells >/dev/null 2>&1 ; then
+   echo "$SMRSH_ALLOWCMD_DIR/smrsh">>/etc/shells
+fi
+
+rm -f $SMRSH_ALLOWCMD_DIR/rsync
+ln -s `which rsync` $SMRSH_ALLOWCMD_DIR/
+
+#2.2 make user(xbaydns) for sync
+#-----------------------------------
 BINDLOG=$BINDCHROOT/var/log/named.log
 rm -rf /home/xbaydns
-rm -f $SMRSH_CMDDIR/rsync
 userdel xbaydns
 groupdel xbaydns
 groupadd xbaydns
-useradd xbaydns -g xbaydns -s $SMRSH_PATH -d /home/xbaydns
-ln -s `which rsync` $SMRSH_CMDDIR/
+useradd xbaydns -g xbaydns -s $SMRSH_CMD -d /home/xbaydns
 mkdir -p /home/xbaydns
 mkdir -p /home/xbaydns/{agent,data,.ssh,view}
 mkdir -p /home/xbaydns/view/{agent_logs,idcview}
@@ -65,16 +75,14 @@ echo "QUERY_LOG_FILE=\"$BINDLOG\"">>/home/xbaydns/agent/agent.conf
 chown -R xbaydns:xbaydns /home/xbaydns
 chmod 700 /home/xbaydns
 
-crontab -l >old_crontab 2>/dev/null
+crontab -l >/home/xbaydns/old_crontab 2>/dev/null
 echo "0-59/5 * * * * /home/xbaydns/agent/Log2IPlist.sh">/tmp/crontab
 crontab /tmp/crontab
 rm -rf /tmp/crontab old_crontab
 
 
 #3.set envionment variables
-#--------------------------
-echo "set the following envionment variables in profile(eg. /etc/profile)"
-echo "you can find the setting in /home/xbaydns/xdenv" 
+#==========================
 echo "\
 XBAYDNS_CHROOT_PATH=$BINDCHROOT
 XBAYDNS_BIND_CONF=/etc
@@ -87,4 +95,17 @@ chmod +x /home/xbaydns/xdenv
 source /home/xbaydns/xdenv
 xdinitbind
 
-echo "done."
+echo "\
+
+
+
+
+----------------------------- Welcome to XBayDNS ---------------------------
+What's the next?
+1. Start named server and make sure named running normally
+   #/usr/local/sbin/named -t $XBAYDNS_CHROOT_PATH -u named
+   #tail -f /var/log/message
+2. Start XBayDNS Master Web server
+   #xdweb
+3. Browse http://$MASTERIP username/password for administrator: admin/admin
+"
