1、smrsh支持CentOS、OpenSuSe、FreeBSD，如果找不到smrsh则出错退出 2、执行前确认rsync，如果找不到，则出错并退出

diff --git a/xbaydns/tools/xdinit b/xbaydns/tools/xdinit
--- a/xbaydns/tools/xdinit
+++ b/xbaydns/tools/xdinit
@@ -1,3 +1,5 @@
+#!/bin/sh
+
 if [ $# != 2 ]; then
     echo "Usage: $0 <master_ip> <path_to_bind_chroot>"
     exit 1
@@ -19,12 +21,37 @@ mknod $BINDCHROOT/dev/null c 1 3
 
 #2.init sync&cron enviroment 
 #-----------------------
+
+if [ -x /usr/sbin/smrsh ];then
+    # CentOS
+    SMRSH_PATH=/usr/sbin/smrsh
+    SMRSH_CMDDIR=/etc/smrsh
+elif [ -x /usr/lib/sendmail.d/bin/smrsh ];then
+    # OpenSuSE
+    SMRSH_PATH=/usr/lib/sendmail.d/bin/smrsh
+    SMRSH_CMDDIR=/usr/lib/sendmail.d/bin
+elif [ -x /usr/libexec/smrsh ];then
+    # FreeBSD
+    SMRSH_PATH=/usr/libexec/smrsh
+    SMRSH_CMDDIR=/usr/libexec/sm.bin
+else
+    echo "Error: can't find smrsh,exiting!"
+    exit 1
+fi
+
+if ! which rsync > /dev/null 2>&1 ; then
+    echo "Error: can't find rsync,exiting!"
+    exit 1
+fi
+
 BINDLOG=$BINDCHROOT/var/log/named.log
 rm -rf /home/xbaydns
+rm -f $SMRSH_CMDDIR/rsync
 userdel xbaydns
 groupdel xbaydns
 groupadd xbaydns
-useradd xbaydns -g xbaydns -s /usr/sbin/smrsh -d /home/xbaydns
+useradd xbaydns -g xbaydns -s $SMRSH_PATH -d /home/xbaydns
+ln -s `which rsync` $SMRSH_CMDDIR/
 mkdir -p /home/xbaydns
 mkdir -p /home/xbaydns/{agent,data,.ssh,view}
 mkdir -p /home/xbaydns/view/{agent_logs,idcview}
@@ -41,7 +68,7 @@ chmod 700 /home/xbaydns
 crontab -l >old_crontab 2>/dev/null
 echo "0-59/5 * * * * /home/xbaydns/agent/Log2IPlist.sh">/tmp/crontab
 crontab /tmp/crontab
-rm -rf /tmp/crontab
+rm -rf /tmp/crontab old_crontab
 
 
 #3.set envionment variables
